version: 2
jobs:
  user-portal:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: cd user-portal
      - restore_cache:
          key: user-portal-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths: ~/.m2
          key: user-portal-{{ checksum "pom.xml" }}
  portal-app:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
      - run: 'cd portal-app'
      - restore_cache:
          key: portal-app-{{ checksum "package-lock.json" }}
      - run: 'npm install'
      - save_cache:
          paths:
            - ./node_modules
          key: portal-app-{{ checksum "package-lock.json" }}
workflows:
  version: 2
  all:
    jobs:
      - user-portal
      - portal-app