version: 2
jobs:
  user-portal:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: user-portal-{{ checksum "user-portal/pom.xml" }}
      - run: mvn -f user-portal/pom.xml package
      - save_cache:
          paths: ~/.m2
          key: user-portal-{{ checksum "user-portal/pom.xml" }}
  portal-app:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: portal-app-{{ checksum "portal-app/package-lock.json" }}
      - run: 'npm --prefix portal-app install'
      - save_cache:
          paths:
            - ./node_modules
          key: portal-app-{{ checksum "portal-app/package-lock.json" }}
workflows:
  version: 2
  all:
    jobs:
      - user-portal
      - portal-app